version: "2"
services:
  auth-ui:
    image: openlmis/dev-ui:5
    ports:
      - "9000:9000"
      - "9876:9876"
    working_dir: /app
    volumes:
      - '.:/app'
    env_file: .env
    volumes_from:
      - ui-components
    depends_on:
      - ui-components
  ui-components:
    image: openlmis/ui-components:5.1.1
    volumes:
      - '/openlmis-ui-components'
  image:
    build: .
    image: openlmis/auth-ui
